### ISSUE TITLE
 error CS0234: The type or namespace name 'Transfer' does not exist in the namespace 'Amazon.S3' (are you missing an assembly reference?)

### ISSUE THREAD

**Issue by CLOUDFIRE91** [awsdocs/amazon-s3-developer-guide#129]
Hi All

I am working in Unity 2018.4.7.. In My project i have to upload the images  from unity. So i have used this aws  code. 

https://docs.aws.amazon.com/AmazonS3/latest/dev/HLuploadFileDotNet.html..

using Amazon;
using Amazon.S3;
using Amazon.S3.Transfer;
using System;
using System.IO;
using System.Threading.Tasks;

namespace Amazon.DocSamples.S3
{
    class UploadFileMPUHighLevelAPITest
    {
        private const string bucketName = "*** provide bucket name ***";
        private const string keyName = "*** provide a name for the uploaded object ***";
        private const string filePath = "*** provide the full path name of the file to upload ***";
        // Specify your bucket region (an example region is shown).
        private static readonly RegionEndpoint bucketRegion = RegionEndpoint.USWest2;
        private static IAmazonS3 s3Client;

        public static void Main()
        {
            s3Client = new AmazonS3Client(bucketRegion);
            UploadFileAsync().Wait();
        }

        private static async Task UploadFileAsync()
        {
            try
            {
                var fileTransferUtility =
                    new TransferUtility(s3Client);

                // Option 1. Upload a file. The file name is used as the object key name.
                await fileTransferUtility.UploadAsync(filePath, bucketName);
                Console.WriteLine("Upload 1 completed");

                // Option 2. Specify object key name explicitly.
                await fileTransferUtility.UploadAsync(filePath, bucketName, keyName);
                Console.WriteLine("Upload 2 completed");

                // Option 3. Upload data from a type of System.IO.Stream.
                using (var fileToUpload = 
                    new FileStream(filePath, FileMode.Open, FileAccess.Read))
                {
                    await fileTransferUtility.UploadAsync(fileToUpload,
                                               bucketName, keyName);
                }
                Console.WriteLine("Upload 3 completed");

                // Option 4. Specify advanced settings.
                var fileTransferUtilityRequest = new TransferUtilityUploadRequest
                {
                    BucketName = bucketName,
                    FilePath = filePath,
                    StorageClass = S3StorageClass.StandardInfrequentAccess,
                    PartSize = 6291456, // 6 MB.
                    Key = keyName,
                    CannedACL = S3CannedACL.PublicRead
                };
                fileTransferUtilityRequest.Metadata.Add("param1", "Value1");
                fileTransferUtilityRequest.Metadata.Add("param2", "Value2");

                await fileTransferUtility.UploadAsync(fileTransferUtilityRequest);
                Console.WriteLine("Upload 4 completed");
            }
            catch (AmazonS3Exception e)
            {
                Console.WriteLine("Error encountered on server. Message:'{0}' when writing an object", e.Message);
            }
            catch (Exception e)
            {
                Console.WriteLine("Unknown encountered on server. Message:'{0}' when writing an object", e.Message);
            }

        }
    }
}

My project settings  Scripting Runtime Version  is 4.x...  When i run the above code in unity. It says 

**error CS0234: The type or namespace name 'Transfer' does not exist in the namespace 'Amazon.S3' (are you missing an assembly reference?**)

I have installed   Aws  AWSSDK.S3.3.3.113.2,AWSSDK.SimpleEmail.3.3.101.193  ... But it shows the above error. 

**I have downgraded to 3.5 framework but it says error CS1644: Feature `asynchronous functions' cannot be used because it is not part of the C# 4.0 language specification**

I have downloaded the Aws  https://docs.aws.amazon.com/sdk-for-net/v3/developer-guide/net-dg-install-assemblies.html  

but it  also not worksw...

How can i solve this error.

**Comment by aws-alan** [comment]
Issue record and will be looked at internally. Documentation will be updated if needed. 

If support is still need please use one of the following-

-     Post your questions on the Amazon S3 discussion forum at https://forums.aws.amazon.com/forum.jspa?forumID=24
-     Contact Technical Support at ​https://aws.amazon.com/contact-us/
